### ISSUE TITLE
Missing port config

### ISSUE THREAD

**Issue by krevsbech** [shmir/PyXenaManager#1]
Minor but leads to falling tests:
PyXenaManager/xenamanager/test/configs/customers/phoenix_port0.xpc is not available hence test_online.py fails.
Is it possible to add the file to git?

**Comment by shmir** [comment]
Test removed altogether as it was old and half baked...
Please note that PyXenaManager is now replaced with PyXenaValkyrie.
If you have prblems migrating to the new project please let me know.
